/* Там, где свет. All characters and scenery are procedural 3D models.
   The supplied videos are references only; no footage or frames are loaded. */
'use strict';
const $=id=>document.getElementById(id), T=window.THREE;
if(!T) { $('error').classList.remove('hidden'); $('error').textContent='Не удалось загрузить 3D-движок. Откройте index.html вместе с папкой vendor.'; throw Error('THREE missing'); }
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), mix=(a,b,t)=>a+(b-a)*t;
let mobileDevice=matchMedia('(any-pointer: coarse)').matches||navigator.maxTouchPoints>0||innerWidth<820;
const lowMemory=mobileDevice&&((navigator.deviceMemory||4)<=2||(navigator.hardwareConcurrency||4)<=2);
const touchAxes={x:0,y:0};let touchRun=false,quality='auto',qualityTier=lowMemory?0:mobileDevice?1:2;
document.body.classList.toggle('touch-device',mobileDevice);
let seed=4317;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const scene=new T.Scene(); scene.background=new T.Color('#c9dfd4');scene.fog=new T.FogExp2('#c9dfd4',.008);
let renderer;try{renderer=new T.WebGLRenderer({antialias:!mobileDevice,powerPreference:mobileDevice?'default':'high-performance',alpha:false});}catch(e){$('error').classList.remove('hidden');$('error').textContent='Для игры нужен браузер с WebGL. Попробуйте открыть игру в Chrome или Safari с включённым аппаратным ускорением.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,mobileDevice?1.15:1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=!lowMemory;renderer.shadowMap.type=mobileDevice?T.PCFShadowMap:T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;$('world').appendChild(renderer.domElement);
const camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,220), clock=new T.Clock();
const hemi=new T.HemisphereLight('#fff4d8','#617c61',2.0);scene.add(hemi);
const sun=new T.DirectionalLight('#ffe3b1',3.3);sun.position.set(-25,40,18);sun.castShadow=true;sun.shadow.mapSize.set(mobileDevice?1024:2048,mobileDevice?1024:2048);Object.assign(sun.shadow.camera,{left:-55,right:55,top:55,bottom:-55,near:1,far:110});sun.shadow.bias=mobileDevice?-.0005:-.00025;sun.shadow.normalBias=mobileDevice?.1:.035;scene.add(sun);sun.target.position.set(0,0,-10);scene.add(sun.target);
const mats={};function mat(c,opts={}){let key=c+JSON.stringify(opts);return mats[key]||(mats[key]=new T.MeshStandardMaterial({color:c,roughness:.85,...opts}));}
const sphereGeo=new T.SphereGeometry(1,mobileDevice?9:12,mobileDevice?6:9),boxGeo=new T.BoxGeometry(1,1,1);
const moving=[],colliders=[],interactions=[],particles=[],lanterns=[],clouds=[];let activeTarget=null;
function mesh(geo,ma,parent,x=0,y=0,z=0,sx=1,sy=1,sz=1){const o=new T.Mesh(geo,typeof ma==='string'?mat(ma):ma);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function ball(p,c,x,y,z,sx,sy=sx,sz=sx){return mesh(sphereGeo,c,p,x,y,z,sx,sy,sz);}
function box(p,c,x,y,z,sx,sy,sz){return mesh(boxGeo,c,p,x,y,z,sx,sy,sz);}
function cyl(p,c,x,y,z,r,h,rt=r,n=9){return mesh(new T.CylinderGeometry(rt,r,h,n),c,p,x,y,z);}
function group(x=0,y=0,z=0,parent=scene){let g=new T.Group();g.position.set(x,y,z);parent.add(g);return g;}
function lineBetween(a,b,r,c,p=scene){const d=new T.Vector3().subVectors(b,a);let o=cyl(p,c,...a.toArray(),r,d.length());o.position.copy(a).addScaledVector(d,.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return o;}
function collider(x,z,w,d){colliders.push({x,z,w:w/2,d:d/2});}
function label(text,x,y,z,size=1.8){const ca=document.createElement('canvas');ca.width=512;ca.height=128;const cx=ca.getContext('2d');cx.fillStyle='#fff6df';cx.beginPath();cx.roundRect(10,10,492,108,28);cx.fill();cx.fillStyle='#426354';cx.textAlign='center';cx.font='bold 35px Segoe UI';cx.fillText(text,256,78);const o=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(ca),depthWrite:false}));o.scale.set(size*3,size*.75,1);o.position.set(x,y,z);scene.add(o);return o;}
// A soft, sunlit miniature valley, with real geometry rather than a background image.
const ground=mesh(new T.PlaneGeometry(220,220), '#8eac76',scene,0,-.025,0);ground.rotation.x=-Math.PI/2;ground.castShadow=false;
function pathRect(x,z,w,d,c='#d5c5a0'){let o=box(scene,c,x,.015,z,w,.06,d);o.castShadow=false;return o;}
pathRect(0,3,8,64);pathRect(1,-28,11,30);pathRect(-9,7,24,5);pathRect(13,21,30,5);pathRect(-6,-14,20,4);
// Thin path borders and rounded stepping stones.
for(let z=-42;z<34;z+=1.4){for(const x of [-4.3,4.3])ball(scene,'#b7b698',x+rand()*.2,.07,z,.28,.15,.35);}
for(let i=0;i<90;i++){let x=(rand()-.5)*7,z=rand()*74-42;ball(scene,'#c3b394',x,.065,z,.15+rand()*.2,.025,.1+rand()*.1);}
// Pond off the path. Entry is blocked; the little wooden bridge is traversable scenery.
const pond=ball(scene,mat('#79b6b2',{roughness:.2,metalness:.25,transparent:true,opacity:.94}),18,.01,-9,7,.09,5);
collider(18,-9,12.2,8.3);const pondRings=[];for(let i=0;i<4;i++){let o=mesh(new T.TorusGeometry(1.2+i*.9,.016,4,64),mat('#d3e9ca',{transparent:true,opacity:.32}),scene,18,.13,-9);o.rotation.x=-Math.PI/2;pondRings.push(o);}
for(let i=0;i<17;i++){const a=i/17*Math.PI*2;ball(scene,'#b6b797',18+Math.cos(a)*7,.1,-9+Math.sin(a)*5,.55,.4,.5);}
for(let i=0;i<7;i++){const x=14+rand()*7,z=-11+rand()*4;let leaf=cyl(scene,'#668f66',x,.16,z,.55,.035);ball(scene,'#edb3b8',x,.25,z,.2,.12,.2);}
const bridge=group(10,0,-9);for(let i=0;i<12;i++)box(bridge,'#b48a5c',0,.22,i*.35-2.1,2,.18,.31);for(const x of [-1,1]){box(bridge,'#e2be83',x,.75,0,.1,.1,4.5);for(const z of [-2,0,2])box(bridge,'#bb9062',x,.45,z,.13,.85,.13);}
function tree(x,z,s=1,color='#7d9b64'){let g=group(x,0,z);cyl(g,'#8b7354',0,1.4*s,0,.21*s,2.8*s,.13*s);for(let i=0;i<7;i++){let a=i*2.4;ball(g,color,Math.cos(a)*.72*s,(2.5+rand()*.85)*s,Math.sin(a)*.72*s,(.95+rand()*.3)*s,1.08*s,.95*s);}collider(x,z,.55*s,.55*s);return g;}
for(let i=0;i<55;i++){let x=(rand()>.5?1:-1)*(12+rand()*31),z=rand()*90-49;if(Math.abs(x-18)<10&&Math.abs(z+9)<8)continue;tree(x,z,.75+rand()*.9,['#759561','#a1af68','#849d61','#c5b36e'][i%4]);}
for(let i=0;i<15;i++){ball(scene,'#9eb686',-65+rand()*130,1,-68-rand()*12,8+rand()*9,3+rand()*6,7+rand()*8);}
function cloud(x,y,z,s){let g=group(x,y,z);for(let i=0;i<5;i++){let o=ball(g,mat('#fff7e5',{roughness:1}),i*1.7-3,Math.sin(i)*.4,0,1.9,1,1.25);o.castShadow=false;}g.scale.setScalar(s);clouds.push(g);}
for(let i=0;i<8;i++)cloud(-70+i*19,20+rand()*9,-48-rand()*20,1.5+rand());
// Warm plaster houses, scalloped roof tiles, shutters, flower boxes and chimneys.
function house(x,z,col,w=5.5,d=5.3,h=4.3){let g=group(x,0,z);box(g,col,0,h/2,0,w,h,d);box(g,'#ece1c5',0,.15,0,w+.15,.3,d+.15);const rw=w/2+.35,rd=d/2+.35,rh=2.1;const roofGeo=new T.BufferGeometry();roofGeo.setAttribute('position',new T.Float32BufferAttribute([-rw,h,-rd,-rw,h,rd,0,h+rh,rd,-rw,h,-rd,0,h+rh,rd,0,h+rh,-rd,0,h+rh,-rd,0,h+rh,rd,rw,h,rd,0,h+rh,-rd,rw,h,rd,rw,h,-rd],3));roofGeo.computeVertexNormals();mesh(roofGeo,mat('#b67560',{side:T.DoubleSide}),g);for(const zz of [-d/2,d/2]){let geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute([-w/2,h,zz,w/2,h,zz,0,h+rh,zz],3));geo.computeVertexNormals();mesh(geo,mat(col,{side:T.DoubleSide}),g);}
for(const side of [-1,1])for(let row=0;row<5;row++)for(let j=0;j<11;j++){let xx=side*(rw-(row+.5)*rw/5);let o=box(g,row%2?'#c38668':'#b7775d',xx,h+(1-Math.abs(xx)/rw)*rh+.055,(j/10-.5)*(d+.2),rw/5*1.23,.065,(d+.3)/11);o.rotation.z=-side*Math.atan(rh/rw);}
box(g,'#efd7b3',w*.26,h+1.5,-.8,.6,1.8,.7);box(g,'#9a6e55',w*.26,h+2.4,-.8,.78,.16,.85);
box(g,'#718778',0,1.05,d/2+.04,1.04,2.05,.14);ball(g,'#e5bd75',.34,1,d/2+.16,.055);
for(const xx of [-w*.3,w*.3]){box(g,'#f5e5c5',xx,2.35,d/2+.07,1.36,1.64,.12);box(g,'#819c99',xx,2.35,d/2+.15,1.04,1.27,.06);box(g,'#f6dfb2',xx,2.35,d/2+.2,.07,1.3,.04);box(g,'#f6dfb2',xx,2.35,d/2+.2,1.08,.06,.04);for(const a of [-1,1])box(g,'#698978',xx+a*.79,2.35,d/2+.13,.32,1.6,.12);box(g,'#ab7d5d',xx,1.45,d/2+.3,1.5,.28,.35);for(let f=0;f<6;f++)ball(g,f%2?'#eda8ad':'#e7ce82',xx-.55+f*.22,1.72,d/2+.3,.15);}
collider(x,z,w+.2,d+.2);return g;}
house(-11,8,'#d9a89d',6,5.5,5);house(12,27,'#e6c896',5.6,5,4.6);house(-12,27,'#d5dbb3',6,5,4.8);house(-14,-18,'#dbb9a0',5,5,4.2);house(13,-30,'#e5cdba',6,5,4.6);house(-15,-37,'#b7c7be',5,5,4.8);
function fence(x,z,n,axis='x'){for(let i=0;i<n;i++){let a=i*.7;box(scene,'#e4d6b5',x+(axis==='x'?a:0),.6,z+(axis==='z'?a:0),.1,1.2,.1);}for(const y of [.35,.9])box(scene,'#dacbac',x+(axis==='x'?(n-1)*.35:0),y,z+(axis==='z'?(n-1)*.35:0),axis==='x'?n*.7:.07,.08,axis==='z'?n*.7:.07);}
fence(-19,13,15);fence(-19,3,15);fence(-19,3,15,'z');fence(7,31,18);fence(-20,-22,16);
// Vineyard pergola inspired by the first walk.
let pergola=group(-8,0,1);for(const x of [-2,2])for(const z of [-2.2,2.2]){box(pergola,'#7b8061',x,1.55,z,.16,3.1,.16);}for(let z=-2.3;z<=2.4;z+=.58)box(pergola,'#997e59',0,3.1,z,4.6,.15,.17);for(let i=0;i<40;i++)ball(pergola,['#6a8a51','#89a165','#a0ac6b'][i%3],(rand()-.5)*4.6,3.18+rand()*.3,(rand()-.5)*4.5,.43,.15,.4);
box(scene,'#bd956c',-11,.7,1,2,.16,.65);for(const xx of [-11.8,-10.2])box(scene,'#856d4f',xx,.35,1,.1,.7,.45);
// Tiny yellow car and a bicycle in the returning-home street.
function car(x,z){let g=group(x,0,z);box(g,'#e6bf61',0,.55,0,1.7,.7,3);ball(g,'#edc965',0,.92,-.2,.86,.63,1.12);box(g,'#819e9e',0,1.14,.3,1.43,.58,.9);box(g,'#edca69',0,1.45,.1,1.5,.12,1.3);for(const xx of [-.85,.85])for(const zz of [-.9,.9]){let o=cyl(g,'#454f48',xx,.32,zz,.32,.22,.32,16);o.rotation.z=Math.PI/2;let hub=cyl(g,'#c9c4aa',xx*1.13,.32,zz,.17,.03,.17,16);hub.rotation.z=Math.PI/2;}for(const xx of [-.5,.5])box(g,mat('#fff0c0',{emissive:'#ffd589',emissiveIntensity:.3}),xx,.64,1.53,.35,.23,.06);collider(x,z,2,3.3);}
car(7,21);car(-7,-31);
for(let i=0;i<20;i++){const a=i/20*Math.PI*2;ball(scene,'#d2c39b',24+Math.cos(a)*3,.15,24+Math.sin(a)*3,.5,.3,.5);}
// Flower meadows are instanced to keep hundreds of stems cheap to draw.
const bladeGeo=new T.ConeGeometry(.075,.48,3),grass=new T.InstancedMesh(bladeGeo,mat('#6d925e'),1500);grass.receiveShadow=true;const dummy=new T.Object3D();for(let i=0;i<1500;i++){let x=(rand()-.5)*94,z=rand()*94-48;if(Math.abs(x)<5||Math.abs(x-18)<8&&Math.abs(z+9)<6)x+=x>0?8:-8;dummy.position.set(x,.17,z);dummy.rotation.set(0,rand()*6,rand()*.3-.15);dummy.scale.setScalar(.6+rand());dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix);}scene.add(grass);
const petalGeo=new T.SphereGeometry(.12,6,4),flowerInst=new T.InstancedMesh(petalGeo,mat('#ffeed0'),450);for(let i=0;i<450;i++){let x=(rand()-.5)*80,z=rand()*85-48;if(Math.abs(x)<5)x+=8*(x>0?1:-1);dummy.position.set(x,.35,z);dummy.rotation.set(0,0,0);dummy.scale.set(1,.45,1);dummy.updateMatrix();flowerInst.setMatrixAt(i,dummy.matrix);flowerInst.setColorAt(i,new T.Color(['#f4d584','#eee7c9','#edb4ae'][i%3]));}scene.add(flowerInst);
// Wheat at the sunset end of the lane.
const wheat=new T.InstancedMesh(new T.CylinderGeometry(.055,.028,.85,4),mat('#c9af72'),550);for(let i=0;i<550;i++){let side=rand()>.5?1:-1;dummy.position.set(side*(6+rand()*8),.4,-36-rand()*14);dummy.rotation.set(rand()*.2,rand()*6,rand()*.25);dummy.scale.setScalar(.7+rand()*.5);dummy.updateMatrix();wheat.setMatrixAt(i,dummy.matrix);}scene.add(wheat);
// Lamp posts and strings of fairy lights, gradually lit by the story.
function lamp(x,z){let g=group(x,0,z);cyl(g,'#697267',0,1.6,0,.07,3.2,.06);box(g,'#777968',0,3.25,0,.46,.08,.46);let bulb=box(g,mat('#ffe1a0',{emissive:'#ffc675',emissiveIntensity:.15}),0,3,0,.3,.4,.3);mesh(new T.ConeGeometry(.38,.3,4),'#737761',g,0,3.44,0);let light=new T.PointLight('#ffd295',0,7,2);light.position.set(0,2.9,0);g.add(light);lanterns.push({bulb,light});}
for(let i=0;i<9;i++)lamp(i%2?4.8:-4.8,28-i*8);
for(let i=0;i<15;i++){let x=-15+i*2;let y=5-.8*Math.sin(i/14*Math.PI);ball(scene,mat('#ffe0a2',{emissive:'#ffbd66',emissiveIntensity:.15}),x,y,20,.085);if(i)lineBetween(new T.Vector3(x-2,5-.8*Math.sin((i-1)/14*Math.PI),20),new T.Vector3(x,y,20),.013,'#737460');}
// Gardens, a tea table and small details make the lane feel lived in.
function flowerBush(x,z,color,s=1){let g=group(x,0,z);ball(g,'#799568',0,.28*s,0,.65*s,.34*s,.55*s);for(let i=0;i<9;i++){const a=i*2.4;ball(g,color,Math.cos(a)*.47*s,.42*s+rand()*.13*s,Math.sin(a)*.4*s,.12*s,.1*s,.12*s);}return g;}
for(const [x,z] of [[-15,11],[-16,7],[-7,4],[-8,13],[9,30],[15,30],[-9,30],[-15,30],[-17,-15],[-10,-16],[9,-27],[17,-27],[-18,-34],[-11,-34],[21,-4],[24,-11]])flowerBush(x,z,['#e6a1a7','#f0c47d','#c7b0d2'][Math.floor(rand()*3)],.9+rand()*.5);
for(let i=0;i<7;i++){let x=-18+i*.5,z=5;box(scene,'#b58d68',x,.14,z,.43,.28,1.2);ball(scene,'#839e65',x,.36,z,.2,.18,.35);}
const teaTable=group(-4,0,26);cyl(teaTable,'#cda679',0,.85,0,1.1,.12,1.1,32);for(const xx of [-.65,.65])for(const zz of [-.5,.5])box(teaTable,'#927859',xx,.42,zz,.09,.8,.09);box(teaTable,'#e7c3a8',0,.92,0,.52,.03,1.95);for(const xx of [-.55,.55]){cyl(teaTable,'#f4e7c7',xx,.94,.15,.23,.035,.23,24);cyl(teaTable,'#a9c6b1',xx,1.04,.15,.12,.17,.14,16);let handle=mesh(new T.TorusGeometry(.075,.023,5,12),'#a9c6b1',teaTable,xx+.14,1.05,.15);handle.rotation.y=Math.PI/2;}
ball(teaTable,'#f2dfba',0,1.13,-.5,.23,.23,.2);cyl(teaTable,'#d6bd8d',0,1.36,-.5,.15,.03);cyl(teaTable,'#b79767',0,.97,.5,.32,.08);for(let i=0;i<6;i++)ball(teaTable,'#a28aaf',Math.cos(i)*.2,1.1,.5+Math.sin(i)*.15,.09);collider(-4,26,1.8,1.8);
for(const xx of [-5.5,-2.5]){box(scene,'#a88964',xx,.47,26,.7,.12,.7);for(const a of [-.23,.23])box(scene,'#9d805f',xx+a,.23,26,.07,.45,.5);box(scene,'#b0956e',xx,.9,25.65,.7,.75,.08);}
for(let i=0;i<65;i++){let x=(rand()-.5)*8,z=rand()*70-39;let leaf=ball(scene,i%2?'#e2b776':'#cdac75',x,.09,z,.10,.012,.06);leaf.rotation.y=rand()*6;}
const mailbox=group(-6,0,15);box(mailbox,'#9d8165',0,.65,0,.12,1.3,.12);box(mailbox,'#98b8ac',0,1.3,0,.65,.42,.4);box(mailbox,'#e9ddbc',0,1.31,.22,.42,.06,.02);box(mailbox,'#c98d77',.35,1.52,0,.03,.24,.19);
// Combine static scenery by material: keep the detailed world at a small draw-call cost.
function compactScenery(){scene.updateMatrixWorld(true);const batches=new Map(),skip=new Set([...clouds,...pondRings]);scene.traverse(o=>{if(!o.isMesh)return;let a=o;while(a){if(skip.has(a))return;a=a.parent;}const key=o.material.uuid+o.castShadow+o.receiveShadow;let b=batches.get(key);if(!b){b={material:o.material,cast:o.castShadow,receive:o.receiveShadow,objects:[]};batches.set(key,b);}b.objects.push(o);});
for(const b of batches.values()){if(b.objects.length<2)continue;let count=0;for(const o of b.objects)count+=o.geometry.index?.count||o.geometry.attributes.position.count;const positions=new Float32Array(count*3),normals=new Float32Array(count*3);let offset=0;const v=new T.Vector3(),n=new T.Vector3(),nm=new T.Matrix3();for(const o of b.objects){let geo=o.geometry,pa=geo.attributes.position,na=geo.attributes.normal,index=geo.index;nm.getNormalMatrix(o.matrixWorld);for(let i=0;i<(index?.count||pa.count);i++){let k=index?index.getX(i):i;v.fromBufferAttribute(pa,k).applyMatrix4(o.matrixWorld);n.fromBufferAttribute(na,k).applyMatrix3(nm).normalize();v.toArray(positions,offset);n.toArray(normals,offset);offset+=3;}o.parent.remove(o);}let geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(positions,3));geo.setAttribute('normal',new T.BufferAttribute(normals,3));geo.computeBoundingSphere();let combined=new T.Mesh(geo,b.material);combined.castShadow=b.cast;combined.receiveShadow=b.receive;scene.add(combined);}}
compactScenery();
// Round little ginger cat, animated legs, ears, scarf, curled tail and whiskers.
function makeCat(){const g=group(),body=ball(g,'#e3b578',0,.52,0,.34,.36,.58);ball(g,'#f7e4ba',0,.41,.4,.22,.2,.19);const head=group(0,.93,.4,g);ball(head,'#e7bc83',0,0,0,.4,.35,.34);for(const x of [-.26,.26]){let ear=mesh(new T.ConeGeometry(.18,.36,3),'#ddaa72',head,x,.29,-.01);ear.rotation.z=x<0?-.23:.23;mesh(new T.ConeGeometry(.11,.24,3),'#eab3a2',head,x,.3,.035);ball(head,'#394a40',x*.65,.015,.302,.05,.07,.033);ball(head,'#fff8db',x*.65-.012,.038,.33,.017);ball(head,'#f7e4c5',x*.37,-.13,.31,.11,.07,.07);}ball(head,'#ba7a72',0,-.085,.371,.05,.034,.025);for(const side of [-1,1])for(let i=0;i<3;i++)lineBetween(new T.Vector3(side*.14,-.1-i*.03,.35),new T.Vector3(side*.4,-.07-i*.07,.35),.006,'#f3e4bf',head);
const legs=[];for(const x of [-.22,.22])for(const z of [-.33,.32])legs.push(ball(g,'#d9a970',x,.19,z,.11,.2,.13));cyl(g,'#789e91',0,.72,.27,.3,.14,.29);let scarf=box(g,'#789e91',-.26,.5,.27,.14,.37,.06);scarf.rotation.z=-.2;
const tail=group(0,.55,-.44,g);const curve=new T.CatmullRomCurve3([new T.Vector3(0,0,0),new T.Vector3(.15,.15,-.25),new T.Vector3(.35,.55,-.3),new T.Vector3(.28,.75,-.22)]);mesh(new T.TubeGeometry(curve,14,.09,7,false),'#d7a46a',tail);return {g,head,legs,tail,body};}
const cat=makeCat();cat.g.position.set(0,0,9);cat.g.rotation.y=Math.PI;
function person(x,z,color='#83b7b0'){let g=group(x,0,z);for(const a of [-.16,.16]){box(g,'#6987a0',a,.43,0,.2,.7,.23);ball(g,'#e8d9bc',a,.09,.1,.16,.1,.25);}ball(g,color,0,1.12,0,.4,.5,.24);cyl(g,'#f0cead',0,1.7,0,.13,.22);ball(g,'#715c50',0,1.99,0,.35,.42,.31);ball(g,'#f2d3b1',0,1.98,.16,.28,.32,.2);ball(g,'#715c50',0,2.2,-.02,.33,.17,.33);for(const xx of [-.09,.09])ball(g,'#46534a',xx,2.02,.35,.023,.032,.016);for(const a of [-1,1]){let arm=ball(g,color,a*.39,1.08,0,.13,.38,.13);arm.rotation.z=a*.17;ball(g,'#efd0ad',a*.43,.76,.01,.11);}box(g,'#65796a',.27,.82,.2,.25,.32,.1);return g;}
const mira=person(-3,6),grandma=person(-6,22,'#c6a6aa');grandma.scale.setScalar(.92);ball(grandma,'#dbd8c1',0,2.25,-.04,.32,.15,.28);
label('Мира',-3,2.95,6,.8);label('Бабушка Роза',-6,2.8,22,.9);
// A sleeping hedgehog rewards exploration with an optional diary note.
let hedgehog=group(23,0,-17);ball(hedgehog,'#927d60',0,.3,0,.5,.3,.4);ball(hedgehog,'#d1b78b',0,.24,.36,.28,.22,.26);for(const x of [-.12,.12])ball(hedgehog,'#394b42',x,.3,.55,.027);for(let i=0;i<18;i++){let s=mesh(new T.ConeGeometry(.09,.23,4),'#6c6750',hedgehog,(rand()-.5)*.7,.48,(rand()-.5)*.6);s.rotation.z=(rand()-.5);}
const butterflyGroups=[];for(let i=0;i<12;i++){let g=group((rand()-.5)*35,1+rand()*2,rand()*70-40);for(const a of [-1,1]){let wing=ball(g,i%2?'#f0c480':'#ddb1b7',a*.15,0,0,.2,.035,.14);wing.userData.side=a;}butterflyGroups.push({g,origin:g.position.clone(),phase:rand()*6});}
let marker=mesh(new T.RingGeometry(.3,.4,30),mat('#fff0bc',{transparent:true,opacity:.8,side:T.DoubleSide}),scene,0,.09,0);marker.rotation.x=-Math.PI/2;marker.visible=false;
function sparkle(pos,c='#ffe2a3',n=14){n=Math.min(n,mobileDevice?12:30);for(let i=0;i<n&&particles.length<60;i++){let o=ball(scene,mat(c,{emissive:c,emissiveIntensity:.6,transparent:true}),pos.x,.5,pos.z,.04);o.castShadow=false;particles.push({o,v:new T.Vector3((rand()-.5)*1.2,.6+rand(),(rand()-.5)*1.2),life:.8});}}
function register(type,g,text,extra={}){const o={type,g,text,...extra};interactions.push(o);return o;}
register('mira',mira,'Поговорить с Мирой');register('grandma',grandma,'Поговорить с бабушкой');register('hedgehog',hedgehog,'Тихонько поздороваться');
const grapes=[],flowers=[],bells=[];
const grapePositions=[[-6,1],[-10,-1],[-7,-3],[-13,1],[-6,11]];
for(let i=0;i<5;i++){let [x,z]=grapePositions[i],g=group(x,.45,z);for(let j=0;j<8;j++)ball(g,j%2?'#9484aa':'#7e759a',Math.cos(j*2.3)*.14,j*.055,Math.sin(j*2.3)*.14,.13);cyl(g,'#81915f',0,.53,0,.025,.16);grapes.push(register('grape',g,'Подобрать виноград',{id:i}));}
const flowerPositions=[[-6,-28],[6,-32],[-8,-39],[7,-43],[0,-46]];
for(let i=0;i<5;i++){let [x,z]=flowerPositions[i],g=group(x,0,z);for(let j=0;j<3;j++){let xx=(j-1)*.22;cyl(g,'#799563',xx,.28,0,.022,.55);for(let p=0;p<5;p++)ball(g,'#f5e5b1',xx+Math.cos(p*1.257)*.13,.59,Math.sin(p*1.257)*.13,.12,.05,.085);ball(g,'#d9b85f',xx,.63,0,.065,.05,.065);}flowers.push(register('flower',g,'Собрать букет',{id:i}));}
const bellColors=['#c4a0bd','#e4bc71','#8bbab0'],bellNames=['Сиреневый','Золотой','Бирюзовый'];
for(let i=0;i<3;i++){let g=group(-2.8+i*2.8,0,18);cyl(g,'#9f8663',0,.75,0,.08,1.5);box(g,'#a78e6b',0,1.55,0,.65,.09,.12);let b=mesh(new T.SphereGeometry(.28,12,9,0,Math.PI*2,0,Math.PI*.65),bellColors[i],g,0,1.16,0);cyl(g,'#b99764',0,.89,0,.055,.23);label(String(i+1),g.position.x,2.1,18,.35);bells.push(register('bell',g,`Позвонить: ${bellNames[i]}`,{id:i,bell:b}));}
const home=group(0,0,28);cyl(home,'#9d835c',0,.56,0,.075,1.12);box(home,'#b89a66',0,1.05,0,.5,.1,.5);let heart=box(home,mat('#ffdf9b',{emissive:'#ffcc79',emissiveIntensity:1.5}),0,1.35,0,.36,.5,.36);for(const xx of [-.23,.23])for(const zz of [-.23,.23])box(home,'#9d835c',xx,1.36,zz,.035,.58,.035);mesh(new T.ConeGeometry(.42,.3,4),'#c4a36a',home,0,1.76,0);let lanternHandle=mesh(new T.TorusGeometry(.12,.025,5,16),'#c4a36a',home,0,1.99,0);register('home',home,'Зажечь фонарь возвращения');label('Праздник возвращения',0,3.5,28,1.2);
const state={stage:0,grapes:[],flowers:[],notes:[],bellIndex:0,bellSolved:false,finished:false};const SAVE='where-light-save-v1';let saved=null;try{saved=JSON.parse(localStorage.getItem(SAVE));if(saved&&saved.version===1)$('resumeButton').classList.remove('hidden');}catch(e){}
let started=false,modal='intro',angle=.25,zoom=21,targetAngle=.25,follow=new T.Vector3(-3,0,4),keys={},moveTarget=null,near=null,time=0,walk=0,toastTimer=0;
const chapters=[['01 / ВИНОГРАДНЫЙ ДВОР','Маленькая помощь','Мира ждёт у тропинки. Подойдите к ней и нажмите E.'],['01 / ВИНОГРАДНЫЙ ДВОР','Сладкий подарок','Соберите 5 гроздей винограда у розового дома и беседки.'],['01 / ВИНОГРАДНЫЙ ДВОР','Корзинка для праздника','Отнесите виноград Мире у начала тропинки.'],['02 / ЗАКАТНОЕ ПОЛЕ','Цветы уходящего дня','Найдите 5 букетиков у дальнего конца тропинки. Жёлтые искры подскажут путь.'],['02 / ЗАКАТНОЕ ПОЛЕ','Вечер в ладонях','Вернитесь к Мире. Она бережно сохранит полевые цветы.'],['03 / УЛИЦА ФОНАРЕЙ','Мелодия возвращения','Бабушка Роза ждёт у жёлтой машины. Узнайте мелодию колокольчиков.'],['03 / УЛИЦА ФОНАРЕЙ','Три маленьких звука','Позвоните: золотой → сиреневый → бирюзовый. Клавиши 2 → 1 → 3 на стойках.'],['03 / УЛИЦА ФОНАРЕЙ','Там, где свет','Подойдите к золотому фонарю в конце улицы и нажмите E.'],['ЭПИЛОГ / ВЕЧЕР ПРОДОЛЖАЕТСЯ','Побудьте дома','Гуляйте, слушайте вечер и загляните в дневник. Спасибо за вашу заботу.']];
function save(){if(!started)return;try{localStorage.setItem(SAVE,JSON.stringify({version:1,...state,position:cat.g.position.toArray(),angle:targetAngle}));}catch(e){}}
function inputText(text){return mobileDevice?text.replaceAll('нажмите E','нажмите кнопку действия справа').replaceAll('нажми E','нажми кнопку действия справа').replaceAll('Клавиши 2 → 1 → 3 на стойках.','Номера колокольчиков: 2 → 1 → 3.').replaceAll('или Esc, чтобы вернуться.','или нажмите ×, чтобы вернуться.'):text;}
function updateQuest(){const q=chapters[state.stage];$('chapter').textContent=q[0];$('questTitle').textContent=q[1];$('questText').textContent=inputText(q[2]);const count=state.stage===1?state.grapes.length:state.stage===3?state.flowers.length:state.stage===6?state.bellIndex:0,total=state.stage===1||state.stage===3?5:state.stage===6?3:0;$('progress').innerHTML=Array.from({length:total},(_,i)=>`<i class="pip ${i<count?'done':''}"></i>`).join('');grapes.forEach(o=>o.g.visible=state.stage>=1&&!state.grapes.includes(o.id));flowers.forEach(o=>o.g.visible=state.stage>=3&&!state.flowers.includes(o.id));save();}
function stage(n){state.stage=n;moveTarget=null;updateQuest();chime([440,554,659],.08);}
function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;toastTimer=3.5;}
let dialogLines=[],dialogIndex=0,dialogDone=null;function dialog(lines,done){modal='dialog';moveTarget=null;keys={};dialogLines=lines;dialogIndex=0;dialogDone=done;$('dialog').classList.remove('hidden');renderDialog();}
function renderDialog(){let l=dialogLines[dialogIndex];$('speaker').textContent=l[0];$('dialogText').textContent=inputText(l[1]);$('nextDialog').innerHTML=dialogIndex===dialogLines.length-1?'Пойдём <span>♡</span>':'Дальше <span>→</span>';}
function nextDialog(){if(dialogIndex<dialogLines.length-1){dialogIndex++;renderDialog();}else{$('dialog').classList.add('hidden');modal=null;let fn=dialogDone;dialogDone=null;fn?.();}}
$('nextDialog').onclick=nextDialog;
function cancelDialog(){$('dialog').classList.add('hidden');modal=$('pause').classList.contains('hidden')?null:'pause';dialogDone=null;}
$('closeDialog').onclick=cancelDialog;
let audioCtx=null,musicEnabled=true,musicTick=0;function initAudio(){try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();}catch(e){}}
function tone(freq,duration=.5,volume=.045,delay=0){if(!musicEnabled||!audioCtx)return;let o=audioCtx.createOscillator(),gain=audioCtx.createGain();o.type='sine';o.frequency.value=freq;const t=audioCtx.currentTime+delay;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.018);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(gain);gain.connect(audioCtx.destination);o.start(t);o.stop(t+duration+.05);}
function chime(notes,spacing=.15){notes.forEach((v,i)=>tone(v,.65,.055,i*spacing));}
function diary(){const entries=[['✿','Виноградный двор','Мира вернулась после долгой поездки и боялась, что здесь всё изменилось. Но виноградная беседка всё так же пахнет летом. Иногда достаточно маленькой корзинки, чтобы сказать: «Мы тебя ждали».',state.notes.includes('yard')],['☼','Закатное поле','Мы пошли вдоль поля туда, где солнце становится мёдом. Мира сказала: «Я думала, что возвращаюсь в место. А оказалось — к людям». Я ответил «мяу». Кажется, она поняла.',state.notes.includes('field')],['✧','Улица фонарей','Золотой, сиреневый, бирюзовый. Бабушка всегда звонила именно так, когда звала домой. Сегодня эту мелодию сыграл кот. И все окна стали чуточку теплее.',state.notes.includes('street')]];
$('memories').innerHTML=entries.map(e=>`<article class="memory ${e[3]?'':'locked'}"><div class="journal-art">${e[3]?e[0]:'· · ·'}</div><div><b>${e[1]}</b><small>${e[3]?e[2]:'Эта страница откроется по ходу истории.'}</small></div></article>`).join('');if(state.notes.includes('hedgehog'))$('memories').innerHTML+='<article class="memory bonus"><div><b>♡ Очень тихое знакомство</b><small>За прудом спал ёж. Я не стал его будить. Забота иногда означает просто дать кому-то отдохнуть.</small></div></article>';
modal='album';keys={};moveTarget=null;$('album').classList.remove('hidden');}
function closeAlbum(){$('album').classList.add('hidden');modal=$('ending').classList.contains('hidden')?(started?null:'intro'):'ending';}
$('albumButton').onclick=diary;$('endingAlbum').onclick=diary;$('closeAlbum').onclick=closeAlbum;
function interact(){if(modal||!near)return;const o=near;moveTarget=null;switch(o.type){case 'mira':
if(state.stage===0)dialog([['МИРА','Привет, Рыжик. Я так давно здесь не была… Даже не знаю, помнит ли этот двор меня.'],['РЫЖИК','Мр-р. Двор помнит запах твоего свитера. А я помню, как ты чесала меня за ухом.'],['МИРА','Бабушка готовит маленький праздник. Поможешь собрать пять гроздей винограда? Они лежат у розового дома и под беседкой.']],()=>stage(1));
else if(state.stage===2)dialog([['МИРА','Какая чудесная корзинка! Я думала, что всё здесь стало чужим. Но ты совсем не изменился.'],['МИРА','Пойдём к полю? Там растут маленькие золотые цветы. Собери пять букетиков для бабушки — у дальнего конца тропинки.'],['РЫЖИК','Если дорога пахнет травой и вечером, по ней обязательно стоит пройти.']],()=>{state.notes.push('yard');stage(3);toast('В дневнике появилась первая страница ✿');});
else if(state.stage===4)dialog([['МИРА','Они пахнут тем самым летом… Спасибо, Рыжик. Теперь я понимаю: дом ждал меня всё это время.'],['МИРА','Осталось зажечь фонари. Бабушка Роза знает их секрет — она стоит у жёлтой машины, в другом конце улицы.']],()=>{state.notes.push('field');stage(5);toast('В дневнике сохранён закат ☼');});
else dialog([['МИРА',state.finished?'Теперь здесь снова пахнет домом. Побудь со мной ещё немного, Рыжик.':state.stage===1?'Я подожду здесь. Ищи фиолетовые грозди рядом с розовым домом и беседкой.':state.stage===3?'Цветы растут у дальнего конца тропинки, за прудом. Не торопись — вечер ещё длинный.':'Бабушка ждёт нас у жёлтой машины. Мне кажется, она приготовила что-то особенное.']]);break;
case 'grandma':if(state.stage===5)dialog([['БАБУШКА РОЗА','Ах, мой маленький помощник. Мира думает, что мы устроили праздник по случаю её приезда. Но мы устраиваем его потому, что она дома.'],['БАБУШКА РОЗА','Фонари слушают нашу старую мелодию: сначала золотой колокольчик, потом сиреневый, потом бирюзовый. Это 2, 1, 3.'],['БАБУШКА РОЗА','Подойди к каждому колокольчику и нажми E. Если ошибёшься, просто начни мелодию заново.']],()=>stage(6));else dialog([['БАБУШКА РОЗА',state.stage>=7?'Какая тёплая мелодия. Последний фонарь ждёт в конце улицы. Зажги его — и мы все соберёмся за столом.':'Я приготовила чай. Помоги Мире с виноградом и цветами, а потом возвращайся ко мне.']]);break;
case 'grape':if(state.stage!==1){toast('Эта гроздь пригодится для праздника');break;}state.grapes.push(o.id);o.g.visible=false;sparkle(o.g.position,'#d6b5e5');chime([523,659]);toast(`Виноград ${state.grapes.length} / 5 ♡`);if(state.grapes.length===5)stage(2);else updateQuest();break;
case 'flower':if(state.stage!==3){toast('Пусть цветы пока греются в солнце');break;}state.flowers.push(o.id);o.g.visible=false;sparkle(o.g.position);chime([587,740]);toast(`Букеты ${state.flowers.length} / 5 ✿`);if(state.flowers.length===5)stage(4);else updateQuest();break;
case 'bell':tone([523,659,784][o.id],1.4,.09);o.ringTime=1.2;if(state.stage===6){if(o.id===[1,0,2][state.bellIndex]){state.bellIndex++;sparkle(o.g.position);if(state.bellIndex===3){state.bellSolved=true;state.notes.push('street');stage(7);toast('Мелодия вспомнилась. Остался последний фонарь ✧');}else{updateQuest();toast(`Верный звук ${state.bellIndex} / 3`);}}else{state.bellIndex=0;updateQuest();toast('Попробуем ещё раз: золотой → сиреневый → бирюзовый');}}break;
case 'hedgehog':if(!state.notes.includes('hedgehog')){state.notes.push('hedgehog');save();toast('Секретная страница: очень тихое знакомство ♡');}dialog([['РЫЖИК','Тс-с… Здесь спит маленький сосед. Я лучше посижу рядом и послушаю, как шуршат листья.']]);break;
case 'home':if(state.stage===7){state.finished=true;stage(8);sparkle(o.g.position,'#ffe4a2',45);dialog([['МИРА','Знаешь, Рыжик… Дом — это не когда всё остаётся прежним. Это когда тебя всё равно ждут.'],['БАБУШКА РОЗА','Чай остывает, мои дорогие. Идите сюда. Сегодня всем найдётся место.'],['РЫЖИК','Я принёс виноград, цветы и немного света. Но самое важное мы нашли по дороге — друг друга.']],()=>{modal='ending';$('ending').classList.remove('hidden');chime([392,494,587,784],.25);});}else if(state.finished)toast('Здесь всегда есть место для маленького кота ♡');else toast('Сначала приготовим праздник и вспомним мелодию фонарей');break;}}
function begin(load=false){Object.assign(state,{stage:0,grapes:[],flowers:[],notes:[],bellIndex:0,bellSolved:false,finished:false});cat.g.position.set(0,0,9);targetAngle=.25;if(load&&saved){Object.assign(state,{stage:clamp(saved.stage||0,0,8),grapes:saved.grapes||[],flowers:saved.flowers||[],notes:saved.notes||[],bellIndex:clamp(saved.bellIndex||0,0,3),bellSolved:!!saved.bellSolved,finished:!!saved.finished});if(saved.position?.length===3)cat.g.position.fromArray(saved.position);targetAngle=saved.angle||.25;}
started=true;modal=null;keys={};moveTarget=null;for(const id of ['intro','pause','ending','album','dialog'])$(id).classList.add('hidden');$('quest').classList.remove('hidden');initAudio();updateQuest();follow.copy(cat.g.position);toast('WASD или клик по земле — гулять. E — поговорить.');}
$('startButton').onclick=()=>begin();$('resumeButton').onclick=()=>begin(true);$('restartButton').onclick=()=>dialog([['НАЧАТЬ ЗАНОВО?','Сохранённая прогулка будет заменена новой историей. Нажмите «Пойдём», чтобы начать, или Esc, чтобы вернуться.']],()=>begin());
function pause(){if(!started||modal)return;modal='pause';keys={};moveTarget=null;save();$('pause').classList.remove('hidden');}
function unpause(){$('pause').classList.add('hidden');modal=null;}
$('pauseButton').onclick=pause;$('continueButton').onclick=unpause;$('freePlayButton').onclick=()=>{$('ending').classList.add('hidden');modal=null;};
$('soundButton').onclick=()=>{musicEnabled=!musicEnabled;initAudio();$('soundButton').textContent=musicEnabled?'♫':'♪̸';$('soundButton').title=musicEnabled?'Выключить звук':'Включить звук';};
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){if(modal==='album')closeAlbum();else if(modal==='pause')unpause();else if(modal==='dialog'){$('dialog').classList.add('hidden');modal=$('pause').classList.contains('hidden')?null:'pause';dialogDone=null;}else pause();return;}if(modal==='dialog'&&['KeyE','Enter','Space'].includes(e.code)){nextDialog();return;}if(!modal){keys[e.code]=true;if(e.code==='KeyE')interact();if(e.code==='KeyJ')diary();if(e.code==='KeyQ')targetAngle-=.35;}});
window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{keys={};pause();});
const raycaster=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0);
function walkToScreen(clientX,clientY){if(!started||modal)return;pointer.set(clientX/innerWidth*2-1,-clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);let p=new T.Vector3();if(raycaster.ray.intersectPlane(plane,p)){moveTarget=new T.Vector3(clamp(p.x,-30,30),0,clamp(p.z,-50,34));marker.position.set(moveTarget.x,.1,moveTarget.z);marker.visible=true;}}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')walkToScreen(e.clientX,e.clientY);});
window.addEventListener('wheel',e=>{if(!modal)zoom=clamp(zoom+e.deltaY*.012,13,32);},{passive:true});
function blocked(x,z){if(x<-32||x>32||z<-51||z>35)return true;return colliders.some(c=>Math.abs(x-c.x)<c.w+.33&&Math.abs(z-c.z)<c.d+.33);}
function validTarget(o){if(!o.g.visible)return false;if(o.type==='grape')return state.stage===1;if(o.type==='flower')return state.stage===3;return true;}
function questTargets(){if(state.stage===1)return grapes.filter(o=>!state.grapes.includes(o.id));if(state.stage===3)return flowers.filter(o=>!state.flowers.includes(o.id));if([0,2,4].includes(state.stage))return interactions.filter(o=>o.type==='mira');if(state.stage===5)return interactions.filter(o=>o.type==='grandma');if(state.stage===6)return bells.slice();if(state.stage===7)return interactions.filter(o=>o.type==='home');return [];}
const beacon=group();const beaconRing=mesh(new T.TorusGeometry(.65,.035,5,40),mat('#fff1b5',{emissive:'#ffcb77',emissiveIntensity:.6,transparent:true,opacity:.85}),beacon);beaconRing.rotation.x=-Math.PI/2;const beaconGem=mesh(new T.OctahedronGeometry(.12),mat('#fff0b7',{emissive:'#ffc26a',emissiveIntensity:.8}),beacon,0,1.9,0);
const map=$('minimap').getContext('2d');function drawMap(){map.clearRect(0,0,160,160);map.fillStyle='#e8ecddeb';map.beginPath();map.arc(80,80,79,0,Math.PI*2);map.fill();map.save();map.beginPath();map.arc(80,80,74,0,Math.PI*2);map.clip();let mx=x=>80+x*1.7,mz=z=>93+z*1.25;map.fillStyle='#d3c7aa';map.fillRect(mx(-4),mz(-50),13.6,108);map.fillStyle='#8aafb0';map.beginPath();map.ellipse(mx(18),mz(-9),12,7,0,0,7);map.fill();map.fillStyle='#acb791';for(const c of colliders){if(c.w>1&&c.x!==18)map.fillRect(mx(c.x-c.w),mz(c.z-c.d),c.w*3.4,c.d*2.5);}for(const o of questTargets()){map.fillStyle='#be934a';map.beginPath();map.arc(mx(o.g.position.x),mz(o.g.position.z),3,0,7);map.fill();}map.fillStyle='#537d67';map.beginPath();map.arc(mx(cat.g.position.x),mz(cat.g.position.z),4,0,7);map.fill();map.restore();map.font='8px Segoe UI';map.fillStyle='#61725e';map.textAlign='center';map.fillText('ПОЛЕ',80,20);map.fillText('ДОМ',80,149);}
const sunDisk=ball(scene,mat('#ffe3ab',{emissive:'#ffd99b',emissiveIntensity:1.2}),-24,15,-70,4);sunDisk.castShadow=false;
const fireflies=[];for(let i=0;i<50;i++){let o=ball(scene,mat('#ffdf9a',{emissive:'#ffc777',emissiveIntensity:1.8,transparent:true}), (rand()-.5)*48, .5+rand()*2,rand()*80-45,.028);o.castShadow=false;fireflies.push({o,p:o.position.clone(),phase:rand()*7});}
let saveTick=0,mapTick=0,evening=0,perfElapsed=0,perfFrames=0,shadowFrame=0;function frame(){requestAnimationFrame(frame);const elapsed=clock.getDelta();if(document.hidden)return;const dt=Math.min(elapsed,.06);time+=dt;
document.body.classList.toggle('playing',started&&!modal);if(modal){touchAxes.x=touchAxes.y=0;}
if(mobileDevice&&quality==='auto'&&started&&!modal){perfElapsed+=elapsed;perfFrames++;if(perfElapsed>8){if(perfFrames/perfElapsed<28&&qualityTier>0){qualityTier--;applyQuality();}perfElapsed=0;perfFrames=0;}}
if(mobileDevice&&!modal&&++shadowFrame%4===0)renderer.shadowMap.needsUpdate=true;
let movingCat=false;if(started&&!modal){let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0)+touchAxes.x,dz=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+touchAxes.y;if(keys.ArrowLeft)targetAngle-=dt*.9;if(keys.ArrowRight)targetAngle+=dt*.9;let dir=new T.Vector3();const force=clamp(Math.hypot(dx,dz),0,1);if(force>.08){moveTarget=null;marker.visible=false;let forward=new T.Vector3(-Math.sin(angle),0,-Math.cos(angle)),right=new T.Vector3(Math.cos(angle),0,-Math.sin(angle));dir.addScaledVector(right,dx).addScaledVector(forward,-dz).normalize();}else if(moveTarget){dir.subVectors(moveTarget,cat.g.position);dir.y=0;if(dir.length()<.25){moveTarget=null;marker.visible=false;}else dir.normalize();}
if(dir.lengthSq()>.001){movingCat=true;const running=keys.ShiftLeft||keys.ShiftRight||touchRun;const speed=(running?6.3:3.8)*(force>.08?Math.max(.3,force):1);const nx=cat.g.position.x+dir.x*dt*speed,nz=cat.g.position.z+dir.z*dt*speed;let moved=false;if(!blocked(nx,cat.g.position.z)){cat.g.position.x=nx;moved=true;}if(!blocked(cat.g.position.x,nz)){cat.g.position.z=nz;moved=true;}if(!moved&&moveTarget){moveTarget=null;marker.visible=false;toast('Обойдём препятствие — выберите свободную тропинку');}let want=Math.atan2(dir.x,dir.z);cat.g.rotation.y+=Math.atan2(Math.sin(want-cat.g.rotation.y),Math.cos(want-cat.g.rotation.y))*Math.min(1,dt*12);walk+=dt*(running?17:12);}
saveTick+=dt;if(saveTick>4){save();saveTick=0;}near=null;let dist=2.2;for(const o of interactions){if(!validTarget(o))continue;let d=cat.g.position.distanceTo(o.g.position);if(d<dist){dist=d;near=o;}}$('prompt').classList.toggle('hidden',!near);if(near)$('prompt').querySelector('span').textContent=near.text;
}else $('prompt').classList.add('hidden');
if(mobileDevice){const action=$('actionTouch');action.disabled=!near||!!modal;action.querySelector('small').textContent=!near?'Подойти':near.type==='grape'||near.type==='flower'?'Взять':near.type==='bell'?'Звонить':near.type==='home'?'Зажечь':'Говорить';action.setAttribute('aria-label',near?.text||'Подойдите к персонажу или предмету');}
cat.legs.forEach((leg,i)=>{leg.position.y=.19+(movingCat?Math.sin(walk+(i%3===0?0:Math.PI))*.085:0);leg.rotation.x=movingCat?Math.sin(walk+(i%3===0?0:Math.PI))*.4:0;});cat.body.position.y=.52+Math.sin(time*2)*.008+(movingCat?Math.sin(walk*2)*.018:0);cat.tail.rotation.z=Math.sin(time*2)*.13;cat.head.rotation.z=Math.sin(time*1.4)*.025;
angle=mix(angle,targetAngle,dt*5);if(started)follow.lerp(cat.g.position,Math.min(1,dt*3.5));else{follow.set(-3,0,4);angle=.38+Math.sin(time*.08)*.07;}
let viewZoom=(started?zoom:25)*(innerWidth<600?1.18:1);camera.position.set(follow.x+Math.sin(angle)*viewZoom,viewZoom*.79,follow.z+Math.cos(angle)*viewZoom);camera.lookAt(follow.x,1,follow.z);
const nightTarget=state.stage>=7?.9:state.stage>=3?.5:0;evening=mix(evening,nightTarget,dt*.25);scene.background.setRGB(mix(.79,.43,evening),mix(.875,.51,evening),mix(.83,.59,evening));scene.fog.color.copy(scene.background);hemi.intensity=mix(2,1.3,evening);sun.intensity=mix(3.3,1.6,evening);sun.color.setRGB(1,mix(.89,.67,evening),mix(.7,.44,evening));renderer.toneMappingExposure=mix(1.18,1.03,evening);for(const l of lanterns){l.bulb.material.emissiveIntensity=mix(.15,1.7,evening);l.light.intensity=evening*3;}
if(started){$('locationName').textContent=cat.g.position.z<-23?'Закатное поле':cat.g.position.z>16?'Улица фонарей':cat.g.position.x>8?'Тихий пруд':'Виноградный двор';}
for(const o of [...grapes,...flowers]){if(o.type==='grape')o.g.position.y=.45+Math.sin(time*2+o.id)*.055;}
for(const b of bells){b.ringTime=Math.max(0,(b.ringTime||0)-dt);b.bell.rotation.z=Math.sin(time*24)*b.ringTime*.3;}
heart.material.emissiveIntensity=1.4+Math.sin(time*2)*.2;home.visible=state.stage>=7;
let targets=questTargets(),closest=targets.sort((a,b)=>a.g.position.distanceToSquared(cat.g.position)-b.g.position.distanceToSquared(cat.g.position))[0];beacon.visible=started&&!!closest;if(closest){beacon.position.set(closest.g.position.x,.11,closest.g.position.z);beaconGem.position.y=2+Math.sin(time*3)*.15;beaconGem.rotation.y=time;beaconRing.scale.setScalar(1+Math.sin(time*2)*.08);}
for(const b of butterflyGroups){b.g.position.set(b.origin.x+Math.sin(time*.7+b.phase)*1.3,b.origin.y+Math.sin(time*2+b.phase)*.3,b.origin.z+Math.cos(time*.6+b.phase));b.g.rotation.y=time*.3+b.phase;for(const w of b.g.children)w.rotation.z=w.userData.side*Math.sin(time*14+b.phase)*.7;}
for(const f of fireflies){f.o.position.set(f.p.x+Math.sin(time+f.phase)*.5,f.p.y+Math.sin(time*1.8+f.phase)*.3,f.p.z+Math.cos(time+f.phase)*.5);f.o.material.opacity=(.3+Math.sin(time*2+f.phase)*.25)*(.3+evening);}
for(const c of clouds)c.position.x+=dt*.13;for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=dt*1.8;p.o.position.addScaledVector(p.v,dt);p.o.scale.setScalar(Math.max(0,p.life)*.04);if(p.life<=0){scene.remove(p.o);particles.splice(i,1);}}
for(let i=0;i<pondRings.length;i++){pondRings[i].scale.setScalar(1+Math.sin(time*.8+i)*.03);}marker.scale.setScalar(1+Math.sin(time*5)*.15);
if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').style.opacity=0;}
musicTick+=dt;if(musicTick>2.4&&started&&musicEnabled){musicTick=0;let notes=[196,247,294,330,294,247,220,294];let i=Math.floor(time/2.4)%notes.length;tone(notes[i],2.6,.025);tone(notes[i]*2,1.9,.009,.4);}
mapTick+=dt;if(mapTick>.12){drawMap();mapTick=0;}renderer.render(scene,camera);}
function resizeGame(){camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<600?49:40;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
window.addEventListener('resize',resizeGame);window.visualViewport?.addEventListener('resize',resizeGame);
function applyQuality(){const tier=quality==='low'?0:quality==='high'?2:qualityTier;renderer.setPixelRatio(Math.min(devicePixelRatio,tier===0?.8:tier===1?1.15:mobileDevice?1.5:1.7));renderer.shadowMap.enabled=tier>0;renderer.shadowMap.autoUpdate=!mobileDevice;renderer.shadowMap.needsUpdate=true;grass.count=tier===0?400:mobileDevice?650:1500;flowerInst.count=tier===0?150:mobileDevice?240:450;wheat.count=tier===0?180:mobileDevice?280:550;clouds.forEach((o,i)=>o.visible=!mobileDevice||i%2===0);butterflyGroups.forEach((o,i)=>o.g.visible=!mobileDevice||i<6);fireflies.forEach((o,i)=>o.o.visible=!mobileDevice||i<(tier===0?12:24));$('qualityButton').title='Качество: '+({auto:'авто',low:'экономное',high:'высокое'}[quality]);}
$('qualityButton').onclick=()=>{quality=quality==='auto'?'low':quality==='low'?'high':'auto';applyQuality();toast('Графика: '+({auto:'автоматическая настройка',low:'экономный режим',high:'высокое качество'}[quality]));};
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();toast('Графика приостановлена. Восстанавливаем…');});renderer.domElement.addEventListener('webglcontextrestored',()=>{applyQuality();toast('Графика восстановлена. Можно продолжать.');});
document.addEventListener('visibilitychange',()=>{keys={};touchAxes.x=touchAxes.y=0;if(document.hidden){pause();audioCtx?.suspend();}else if(musicEnabled)audioCtx?.resume();});
applyQuality();resizeGame();updateQuest();frame();
